package netPack;

/**
 * Class that holds the information for a key event that will be send over the socket
 * 
 * @author Carl
 *
 */

public class KeyEventRAT {
	
	private int keyCode;
	
	public KeyEventRAT(int keyCode){
		this.setKeyCode(keyCode);
	}

	/** 
	 *  Bellow this comment is autogenerated getters and setters from eclipse..
	 */
	
	public int getKeyCode() {
		return keyCode;
	}

	public void setKeyCode(int keyCode) {
		this.keyCode = keyCode;
	}
}
